### ISSUE TITLE
Plugin generates duplicate constants

### ISSUE THREAD

**Issue by mintdaniel42** [cthing/gradle-property-key-constants#1]
If we have two properties files whose map keys overlap but are not the same (for example feature flags in prod / test) they are not replaced but written twice (or more)

**Comment by baron1405** [comment]
To make sure I understand the issue, you have something like:

prod.properties
```
key1=hello
key2=world
```
test.properties
```
key1=foo
key3=bar
```
when you point the plugin at both property files you end up with a constants source file with:
```java
static final String PROD_KEY1 = "hello";
static final String PROD_KEY2 = "world";

static final String TEST_KEY1 = "foo";
static final String TEST_KEY3 = "bar";
```

If that is the case, this is by design. If you want to merge properties files, consider separating out the common properties to a properties file and leave only the prod-specific and test-specific properties in the other files. In your build, you point the plugin at the common and prod or common and test properties depending on whether you are testing. Typically though, that kind of use case is handled at runtime and only the common properties file would be compiled in.

**Comment by mintdaniel42** [comment]
Oh okay thank you 😄 Have a great day 🖖🏼
